/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package chargingcdr;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class CorrelationID implements Serializable {

	private static final long serialVersionUID = 1L;

	public byte[] code = null;
	private CallReferenceNumber callReference = null;
	private ChargingID chargingID = null;
	private AccountingCorrelationID accountingCorrelationID = null;
	private DccCorrelationID dccCorrelationId = null;
	
	public CorrelationID() {
	}

	public CorrelationID(byte[] code) {
		this.code = code;
	}

	public void setCallReference(CallReferenceNumber callReference) {
		this.callReference = callReference;
	}

	public CallReferenceNumber getCallReference() {
		return callReference;
	}

	public void setChargingID(ChargingID chargingID) {
		this.chargingID = chargingID;
	}

	public ChargingID getChargingID() {
		return chargingID;
	}

	public void setAccountingCorrelationID(AccountingCorrelationID accountingCorrelationID) {
		this.accountingCorrelationID = accountingCorrelationID;
	}

	public AccountingCorrelationID getAccountingCorrelationID() {
		return accountingCorrelationID;
	}

	public void setDccCorrelationId(DccCorrelationID dccCorrelationId) {
		this.dccCorrelationId = dccCorrelationId;
	}

	public DccCorrelationID getDccCorrelationId() {
		return dccCorrelationId;
	}

	public int encode(OutputStream os) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			return code.length;
		}

		int codeLength = 0;
		if (dccCorrelationId != null) {
			codeLength += dccCorrelationId.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 3
			os.write(0xA3);
			codeLength += 1;
			return codeLength;
		}
		
		if (accountingCorrelationID != null) {
			codeLength += accountingCorrelationID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 2
			os.write(0x82);
			codeLength += 1;
			return codeLength;
		}
		
		if (chargingID != null) {
			codeLength += chargingID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			os.write(0x81);
			codeLength += 1;
			return codeLength;
		}
		
		if (callReference != null) {
			codeLength += callReference.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			os.write(0x80);
			codeLength += 1;
			return codeLength;
		}
		
		throw new IOException("Error encoding CHOICE: No element of CHOICE was selected.");
	}

	public int decode(InputStream is) throws IOException {
		return decode(is, null);
	}

	public int decode(InputStream is, BerTag berTag) throws IOException {

		int codeLength = 0;
		BerTag passedTag = berTag;

		if (berTag == null) {
			berTag = new BerTag();
			codeLength += berTag.decode(is);
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			callReference = new CallReferenceNumber();
			codeLength += callReference.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			chargingID = new ChargingID();
			codeLength += chargingID.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			accountingCorrelationID = new AccountingCorrelationID();
			codeLength += accountingCorrelationID.decode(is, false);
			return codeLength;
		}

		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 3)) {
			dccCorrelationId = new DccCorrelationID();
			codeLength += dccCorrelationId.decode(is, false);
			return codeLength;
		}

		if (passedTag != null) {
			return 0;
		}

		throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		if (callReference != null) {
			sb.append("callReference: ").append(callReference);
			return;
		}

		if (chargingID != null) {
			sb.append("chargingID: ").append(chargingID);
			return;
		}

		if (accountingCorrelationID != null) {
			sb.append("accountingCorrelationID: ").append(accountingCorrelationID);
			return;
		}

		if (dccCorrelationId != null) {
			sb.append("dccCorrelationId: ");
			dccCorrelationId.appendAsString(sb, indentLevel + 1);
			return;
		}

		sb.append("<none>");
	}

}

