/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package chargingcdr;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class DiameterCreditControlRecord implements Serializable {

	private static final long serialVersionUID = 1L;

	public static class AccumulatorValueInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.AccumulatorValueInfo> seqOf = null;

		public AccumulatorValueInfo() {
			seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
		}

		public AccumulatorValueInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.AccumulatorValueInfo> getAccumulatorValueInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.AccumulatorValueInfo element = new chargingcdr.AccumulatorValueInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.AccumulatorValueInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class DedicatedAccountInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.DedicatedAccountInfo> seqOf = null;

		public DedicatedAccountInfo() {
			seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
		}

		public DedicatedAccountInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.DedicatedAccountInfo> getDedicatedAccountInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.DedicatedAccountInfo element = new chargingcdr.DedicatedAccountInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.DedicatedAccountInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class CommunityDataInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.CommunityDataInfo> seqOf = null;

		public CommunityDataInfo() {
			seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
		}

		public CommunityDataInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.CommunityDataInfo> getCommunityDataInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.CommunityDataInfo element = new chargingcdr.CommunityDataInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.CommunityDataInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private CdrReason cdrReason = null;
	private NodeID nodeID = null;
	private RecordSequenceNumber recordSequenceNumber = null;
	private BerBoolean lastPartialOutput = null;
	private TrafficCase trafficCase = null;
	private TeleServiceCode teleServiceCode = null;
	private AddressString subscriberID = null;
	private AddressString callingPartyNumber = null;
	private AddressString calledPartyNumber = null;
	private TimeStamp triggerTime = null;
	private ChargedDuration chargedDuration = null;
	private DataVolume dataVolume = null;
	private NumberOfEvents numberOfEvents = null;
	private MoneyAmount finalCharge = null;
	private MoneyAmount accountValueBefore = null;
	private MoneyAmount accountValueAfter = null;
	private SessionID sessionID = null;
	private UserName userName = null;
	private NumberOfSDPInterrogations numberOfSDPInterrogations = null;
	private OriginRealm originRealm = null;
	private OriginHost originHost = null;
	private ServiceClass serviceClass = null;
	private AddressString accountNumber = null;
	private LocalSequenceNumber localSequenceNumber = null;
	private FamilyAndFriendsIndicator familyAndFriendsIndicator = null;
	private CurrencyType currencyType = null;
	private AccumulatorValueInfo accumulatorValueInfo = null;
	private DedicatedAccountInfo dedicatedAccountInfo = null;
	private ServiceProviderID serviceProviderID = null;
	private ExtInt extInt1 = null;
	private ExtInt extInt2 = null;
	private ExtInt extInt3 = null;
	private ExtInt extInt4 = null;
	private ExtText extText = null;
	private GPRSQoS gprsQoS = null;
	private AddressString redirectingPartyNumber = null;
	private AddressString originatingLocationInfo = null;
	private AddressString terminatingLocationInfo = null;
	private NetworkID networkID = null;
	private SubscriptionType subscriptionType = null;
	private SmsDeliveryStatus smsDeliveryStatus = null;
	private AddressString calledPartyNumber2 = null;
	private AddressString calledPartyNumber3 = null;
	private RadiusSessionID radiusSessionID = null;
	private MultiSessionID multiSessionID = null;
	private SubscriptionIDData originalSubscriptionIDData = null;
	private SubscriptionIDType originalSubscriptionIDType = null;
	private AccountingCorrelationID accountingCorrelationID = null;
	private AbnormalTerminationReason abnormalTerminationReason = null;
	private AccountGroupID accountGroupID = null;
	private ServiceOfferings serviceOfferings = null;
	private CommunityDataInfo communityDataInfo = null;
	private MoneyAmount usedAmountLastInterval = null;
	private MoneyAmount deductedAmountLastInterval = null;
	private CategorizationInformation categorizationInformation = null;
	private RatedDurations ratedDurations = null;
	
	public DiameterCreditControlRecord() {
	}

	public DiameterCreditControlRecord(byte[] code) {
		this.code = code;
	}

	public void setCdrReason(CdrReason cdrReason) {
		this.cdrReason = cdrReason;
	}

	public CdrReason getCdrReason() {
		return cdrReason;
	}

	public void setNodeID(NodeID nodeID) {
		this.nodeID = nodeID;
	}

	public NodeID getNodeID() {
		return nodeID;
	}

	public void setRecordSequenceNumber(RecordSequenceNumber recordSequenceNumber) {
		this.recordSequenceNumber = recordSequenceNumber;
	}

	public RecordSequenceNumber getRecordSequenceNumber() {
		return recordSequenceNumber;
	}

	public void setLastPartialOutput(BerBoolean lastPartialOutput) {
		this.lastPartialOutput = lastPartialOutput;
	}

	public BerBoolean getLastPartialOutput() {
		return lastPartialOutput;
	}

	public void setTrafficCase(TrafficCase trafficCase) {
		this.trafficCase = trafficCase;
	}

	public TrafficCase getTrafficCase() {
		return trafficCase;
	}

	public void setTeleServiceCode(TeleServiceCode teleServiceCode) {
		this.teleServiceCode = teleServiceCode;
	}

	public TeleServiceCode getTeleServiceCode() {
		return teleServiceCode;
	}

	public void setSubscriberID(AddressString subscriberID) {
		this.subscriberID = subscriberID;
	}

	public AddressString getSubscriberID() {
		return subscriberID;
	}

	public void setCallingPartyNumber(AddressString callingPartyNumber) {
		this.callingPartyNumber = callingPartyNumber;
	}

	public AddressString getCallingPartyNumber() {
		return callingPartyNumber;
	}

	public void setCalledPartyNumber(AddressString calledPartyNumber) {
		this.calledPartyNumber = calledPartyNumber;
	}

	public AddressString getCalledPartyNumber() {
		return calledPartyNumber;
	}

	public void setTriggerTime(TimeStamp triggerTime) {
		this.triggerTime = triggerTime;
	}

	public TimeStamp getTriggerTime() {
		return triggerTime;
	}

	public void setChargedDuration(ChargedDuration chargedDuration) {
		this.chargedDuration = chargedDuration;
	}

	public ChargedDuration getChargedDuration() {
		return chargedDuration;
	}

	public void setDataVolume(DataVolume dataVolume) {
		this.dataVolume = dataVolume;
	}

	public DataVolume getDataVolume() {
		return dataVolume;
	}

	public void setNumberOfEvents(NumberOfEvents numberOfEvents) {
		this.numberOfEvents = numberOfEvents;
	}

	public NumberOfEvents getNumberOfEvents() {
		return numberOfEvents;
	}

	public void setFinalCharge(MoneyAmount finalCharge) {
		this.finalCharge = finalCharge;
	}

	public MoneyAmount getFinalCharge() {
		return finalCharge;
	}

	public void setAccountValueBefore(MoneyAmount accountValueBefore) {
		this.accountValueBefore = accountValueBefore;
	}

	public MoneyAmount getAccountValueBefore() {
		return accountValueBefore;
	}

	public void setAccountValueAfter(MoneyAmount accountValueAfter) {
		this.accountValueAfter = accountValueAfter;
	}

	public MoneyAmount getAccountValueAfter() {
		return accountValueAfter;
	}

	public void setSessionID(SessionID sessionID) {
		this.sessionID = sessionID;
	}

	public SessionID getSessionID() {
		return sessionID;
	}

	public void setUserName(UserName userName) {
		this.userName = userName;
	}

	public UserName getUserName() {
		return userName;
	}

	public void setNumberOfSDPInterrogations(NumberOfSDPInterrogations numberOfSDPInterrogations) {
		this.numberOfSDPInterrogations = numberOfSDPInterrogations;
	}

	public NumberOfSDPInterrogations getNumberOfSDPInterrogations() {
		return numberOfSDPInterrogations;
	}

	public void setOriginRealm(OriginRealm originRealm) {
		this.originRealm = originRealm;
	}

	public OriginRealm getOriginRealm() {
		return originRealm;
	}

	public void setOriginHost(OriginHost originHost) {
		this.originHost = originHost;
	}

	public OriginHost getOriginHost() {
		return originHost;
	}

	public void setServiceClass(ServiceClass serviceClass) {
		this.serviceClass = serviceClass;
	}

	public ServiceClass getServiceClass() {
		return serviceClass;
	}

	public void setAccountNumber(AddressString accountNumber) {
		this.accountNumber = accountNumber;
	}

	public AddressString getAccountNumber() {
		return accountNumber;
	}

	public void setLocalSequenceNumber(LocalSequenceNumber localSequenceNumber) {
		this.localSequenceNumber = localSequenceNumber;
	}

	public LocalSequenceNumber getLocalSequenceNumber() {
		return localSequenceNumber;
	}

	public void setFamilyAndFriendsIndicator(FamilyAndFriendsIndicator familyAndFriendsIndicator) {
		this.familyAndFriendsIndicator = familyAndFriendsIndicator;
	}

	public FamilyAndFriendsIndicator getFamilyAndFriendsIndicator() {
		return familyAndFriendsIndicator;
	}

	public void setCurrencyType(CurrencyType currencyType) {
		this.currencyType = currencyType;
	}

	public CurrencyType getCurrencyType() {
		return currencyType;
	}

	public void setAccumulatorValueInfo(AccumulatorValueInfo accumulatorValueInfo) {
		this.accumulatorValueInfo = accumulatorValueInfo;
	}

	public AccumulatorValueInfo getAccumulatorValueInfo() {
		return accumulatorValueInfo;
	}

	public void setDedicatedAccountInfo(DedicatedAccountInfo dedicatedAccountInfo) {
		this.dedicatedAccountInfo = dedicatedAccountInfo;
	}

	public DedicatedAccountInfo getDedicatedAccountInfo() {
		return dedicatedAccountInfo;
	}

	public void setServiceProviderID(ServiceProviderID serviceProviderID) {
		this.serviceProviderID = serviceProviderID;
	}

	public ServiceProviderID getServiceProviderID() {
		return serviceProviderID;
	}

	public void setExtInt1(ExtInt extInt1) {
		this.extInt1 = extInt1;
	}

	public ExtInt getExtInt1() {
		return extInt1;
	}

	public void setExtInt2(ExtInt extInt2) {
		this.extInt2 = extInt2;
	}

	public ExtInt getExtInt2() {
		return extInt2;
	}

	public void setExtInt3(ExtInt extInt3) {
		this.extInt3 = extInt3;
	}

	public ExtInt getExtInt3() {
		return extInt3;
	}

	public void setExtInt4(ExtInt extInt4) {
		this.extInt4 = extInt4;
	}

	public ExtInt getExtInt4() {
		return extInt4;
	}

	public void setExtText(ExtText extText) {
		this.extText = extText;
	}

	public ExtText getExtText() {
		return extText;
	}

	public void setGprsQoS(GPRSQoS gprsQoS) {
		this.gprsQoS = gprsQoS;
	}

	public GPRSQoS getGprsQoS() {
		return gprsQoS;
	}

	public void setRedirectingPartyNumber(AddressString redirectingPartyNumber) {
		this.redirectingPartyNumber = redirectingPartyNumber;
	}

	public AddressString getRedirectingPartyNumber() {
		return redirectingPartyNumber;
	}

	public void setOriginatingLocationInfo(AddressString originatingLocationInfo) {
		this.originatingLocationInfo = originatingLocationInfo;
	}

	public AddressString getOriginatingLocationInfo() {
		return originatingLocationInfo;
	}

	public void setTerminatingLocationInfo(AddressString terminatingLocationInfo) {
		this.terminatingLocationInfo = terminatingLocationInfo;
	}

	public AddressString getTerminatingLocationInfo() {
		return terminatingLocationInfo;
	}

	public void setNetworkID(NetworkID networkID) {
		this.networkID = networkID;
	}

	public NetworkID getNetworkID() {
		return networkID;
	}

	public void setSubscriptionType(SubscriptionType subscriptionType) {
		this.subscriptionType = subscriptionType;
	}

	public SubscriptionType getSubscriptionType() {
		return subscriptionType;
	}

	public void setSmsDeliveryStatus(SmsDeliveryStatus smsDeliveryStatus) {
		this.smsDeliveryStatus = smsDeliveryStatus;
	}

	public SmsDeliveryStatus getSmsDeliveryStatus() {
		return smsDeliveryStatus;
	}

	public void setCalledPartyNumber2(AddressString calledPartyNumber2) {
		this.calledPartyNumber2 = calledPartyNumber2;
	}

	public AddressString getCalledPartyNumber2() {
		return calledPartyNumber2;
	}

	public void setCalledPartyNumber3(AddressString calledPartyNumber3) {
		this.calledPartyNumber3 = calledPartyNumber3;
	}

	public AddressString getCalledPartyNumber3() {
		return calledPartyNumber3;
	}

	public void setRadiusSessionID(RadiusSessionID radiusSessionID) {
		this.radiusSessionID = radiusSessionID;
	}

	public RadiusSessionID getRadiusSessionID() {
		return radiusSessionID;
	}

	public void setMultiSessionID(MultiSessionID multiSessionID) {
		this.multiSessionID = multiSessionID;
	}

	public MultiSessionID getMultiSessionID() {
		return multiSessionID;
	}

	public void setOriginalSubscriptionIDData(SubscriptionIDData originalSubscriptionIDData) {
		this.originalSubscriptionIDData = originalSubscriptionIDData;
	}

	public SubscriptionIDData getOriginalSubscriptionIDData() {
		return originalSubscriptionIDData;
	}

	public void setOriginalSubscriptionIDType(SubscriptionIDType originalSubscriptionIDType) {
		this.originalSubscriptionIDType = originalSubscriptionIDType;
	}

	public SubscriptionIDType getOriginalSubscriptionIDType() {
		return originalSubscriptionIDType;
	}

	public void setAccountingCorrelationID(AccountingCorrelationID accountingCorrelationID) {
		this.accountingCorrelationID = accountingCorrelationID;
	}

	public AccountingCorrelationID getAccountingCorrelationID() {
		return accountingCorrelationID;
	}

	public void setAbnormalTerminationReason(AbnormalTerminationReason abnormalTerminationReason) {
		this.abnormalTerminationReason = abnormalTerminationReason;
	}

	public AbnormalTerminationReason getAbnormalTerminationReason() {
		return abnormalTerminationReason;
	}

	public void setAccountGroupID(AccountGroupID accountGroupID) {
		this.accountGroupID = accountGroupID;
	}

	public AccountGroupID getAccountGroupID() {
		return accountGroupID;
	}

	public void setServiceOfferings(ServiceOfferings serviceOfferings) {
		this.serviceOfferings = serviceOfferings;
	}

	public ServiceOfferings getServiceOfferings() {
		return serviceOfferings;
	}

	public void setCommunityDataInfo(CommunityDataInfo communityDataInfo) {
		this.communityDataInfo = communityDataInfo;
	}

	public CommunityDataInfo getCommunityDataInfo() {
		return communityDataInfo;
	}

	public void setUsedAmountLastInterval(MoneyAmount usedAmountLastInterval) {
		this.usedAmountLastInterval = usedAmountLastInterval;
	}

	public MoneyAmount getUsedAmountLastInterval() {
		return usedAmountLastInterval;
	}

	public void setDeductedAmountLastInterval(MoneyAmount deductedAmountLastInterval) {
		this.deductedAmountLastInterval = deductedAmountLastInterval;
	}

	public MoneyAmount getDeductedAmountLastInterval() {
		return deductedAmountLastInterval;
	}

	public void setCategorizationInformation(CategorizationInformation categorizationInformation) {
		this.categorizationInformation = categorizationInformation;
	}

	public CategorizationInformation getCategorizationInformation() {
		return categorizationInformation;
	}

	public void setRatedDurations(RatedDurations ratedDurations) {
		this.ratedDurations = ratedDurations;
	}

	public RatedDurations getRatedDurations() {
		return ratedDurations;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (ratedDurations != null) {
			codeLength += ratedDurations.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 55
			os.write(0x37);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (categorizationInformation != null) {
			codeLength += categorizationInformation.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 54
			os.write(0x36);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (deductedAmountLastInterval != null) {
			codeLength += deductedAmountLastInterval.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 53
			os.write(0x35);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (usedAmountLastInterval != null) {
			codeLength += usedAmountLastInterval.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 52
			os.write(0x34);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (communityDataInfo != null) {
			codeLength += communityDataInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 51
			os.write(0x33);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (serviceOfferings != null) {
			codeLength += serviceOfferings.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 50
			os.write(0x32);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (accountGroupID != null) {
			codeLength += accountGroupID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 49
			os.write(0x31);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (abnormalTerminationReason != null) {
			codeLength += abnormalTerminationReason.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 48
			os.write(0x30);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (accountingCorrelationID != null) {
			codeLength += accountingCorrelationID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 47
			os.write(0x2F);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (originalSubscriptionIDType != null) {
			codeLength += originalSubscriptionIDType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 46
			os.write(0x2E);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (originalSubscriptionIDData != null) {
			codeLength += originalSubscriptionIDData.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 45
			os.write(0x2D);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (multiSessionID != null) {
			codeLength += multiSessionID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 44
			os.write(0x2C);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (radiusSessionID != null) {
			codeLength += radiusSessionID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 43
			os.write(0x2B);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (calledPartyNumber3 != null) {
			codeLength += calledPartyNumber3.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 42
			os.write(0x2A);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (calledPartyNumber2 != null) {
			codeLength += calledPartyNumber2.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 41
			os.write(0x29);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (smsDeliveryStatus != null) {
			codeLength += smsDeliveryStatus.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 40
			os.write(0x28);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (subscriptionType != null) {
			codeLength += subscriptionType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 39
			os.write(0x27);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (networkID != null) {
			codeLength += networkID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 38
			os.write(0x26);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (terminatingLocationInfo != null) {
			codeLength += terminatingLocationInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 37
			os.write(0x25);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (originatingLocationInfo != null) {
			codeLength += originatingLocationInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 36
			os.write(0x24);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (redirectingPartyNumber != null) {
			codeLength += redirectingPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 35
			os.write(0x23);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (gprsQoS != null) {
			codeLength += gprsQoS.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 34
			os.write(0x22);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (extText != null) {
			codeLength += extText.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 33
			os.write(0x21);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (extInt4 != null) {
			codeLength += extInt4.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 32
			os.write(0x20);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (extInt3 != null) {
			codeLength += extInt3.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 31
			os.write(0x1F);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (extInt2 != null) {
			codeLength += extInt2.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 30
			os.write(0x9E);
			codeLength += 1;
		}
		
		if (extInt1 != null) {
			codeLength += extInt1.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 29
			os.write(0x9D);
			codeLength += 1;
		}
		
		if (serviceProviderID != null) {
			codeLength += serviceProviderID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 28
			os.write(0x9C);
			codeLength += 1;
		}
		
		if (dedicatedAccountInfo != null) {
			codeLength += dedicatedAccountInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 27
			os.write(0xBB);
			codeLength += 1;
		}
		
		if (accumulatorValueInfo != null) {
			codeLength += accumulatorValueInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 26
			os.write(0xBA);
			codeLength += 1;
		}
		
		if (currencyType != null) {
			codeLength += currencyType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 25
			os.write(0x99);
			codeLength += 1;
		}
		
		if (familyAndFriendsIndicator != null) {
			codeLength += familyAndFriendsIndicator.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 24
			os.write(0x98);
			codeLength += 1;
		}
		
		codeLength += localSequenceNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 23
		os.write(0x97);
		codeLength += 1;
		
		if (accountNumber != null) {
			codeLength += accountNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 22
			os.write(0x96);
			codeLength += 1;
		}
		
		if (serviceClass != null) {
			codeLength += serviceClass.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 21
			os.write(0x95);
			codeLength += 1;
		}
		
		if (originHost != null) {
			codeLength += originHost.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 20
			os.write(0x94);
			codeLength += 1;
		}
		
		if (originRealm != null) {
			codeLength += originRealm.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 19
			os.write(0x93);
			codeLength += 1;
		}
		
		codeLength += numberOfSDPInterrogations.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 18
		os.write(0x92);
		codeLength += 1;
		
		if (userName != null) {
			codeLength += userName.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 17
			os.write(0x91);
			codeLength += 1;
		}
		
		codeLength += sessionID.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 16
		os.write(0x90);
		codeLength += 1;
		
		if (accountValueAfter != null) {
			codeLength += accountValueAfter.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 15
			os.write(0x8F);
			codeLength += 1;
		}
		
		if (accountValueBefore != null) {
			codeLength += accountValueBefore.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 14
			os.write(0x8E);
			codeLength += 1;
		}
		
		if (finalCharge != null) {
			codeLength += finalCharge.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 13
			os.write(0x8D);
			codeLength += 1;
		}
		
		if (numberOfEvents != null) {
			codeLength += numberOfEvents.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 12
			os.write(0x8C);
			codeLength += 1;
		}
		
		if (dataVolume != null) {
			codeLength += dataVolume.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 11
			os.write(0x8B);
			codeLength += 1;
		}
		
		if (chargedDuration != null) {
			codeLength += chargedDuration.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 10
			os.write(0x8A);
			codeLength += 1;
		}
		
		if (triggerTime != null) {
			codeLength += triggerTime.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 9
			os.write(0x89);
			codeLength += 1;
		}
		
		if (calledPartyNumber != null) {
			codeLength += calledPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 8
			os.write(0x88);
			codeLength += 1;
		}
		
		if (callingPartyNumber != null) {
			codeLength += callingPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 7
			os.write(0x87);
			codeLength += 1;
		}
		
		if (subscriberID != null) {
			codeLength += subscriberID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 6
			os.write(0x86);
			codeLength += 1;
		}
		
		if (teleServiceCode != null) {
			codeLength += teleServiceCode.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 5
			os.write(0x85);
			codeLength += 1;
		}
		
		if (trafficCase != null) {
			codeLength += trafficCase.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 4
			os.write(0x84);
			codeLength += 1;
		}
		
		codeLength += lastPartialOutput.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 3
		os.write(0x83);
		codeLength += 1;
		
		codeLength += recordSequenceNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		os.write(0x82);
		codeLength += 1;
		
		codeLength += nodeID.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		os.write(0x81);
		codeLength += 1;
		
		codeLength += cdrReason.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		os.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			cdrReason = new CdrReason();
			subCodeLength += cdrReason.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			nodeID = new NodeID();
			subCodeLength += nodeID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			recordSequenceNumber = new RecordSequenceNumber();
			subCodeLength += recordSequenceNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			lastPartialOutput = new BerBoolean();
			subCodeLength += lastPartialOutput.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			trafficCase = new TrafficCase();
			subCodeLength += trafficCase.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			teleServiceCode = new TeleServiceCode();
			subCodeLength += teleServiceCode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 6)) {
			subscriberID = new AddressString();
			subCodeLength += subscriberID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 7)) {
			callingPartyNumber = new AddressString();
			subCodeLength += callingPartyNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 8)) {
			calledPartyNumber = new AddressString();
			subCodeLength += calledPartyNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 9)) {
			triggerTime = new TimeStamp();
			subCodeLength += triggerTime.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 10)) {
			chargedDuration = new ChargedDuration();
			subCodeLength += chargedDuration.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 11)) {
			dataVolume = new DataVolume();
			subCodeLength += dataVolume.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 12)) {
			numberOfEvents = new NumberOfEvents();
			subCodeLength += numberOfEvents.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 13)) {
			finalCharge = new MoneyAmount();
			subCodeLength += finalCharge.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 14)) {
			accountValueBefore = new MoneyAmount();
			subCodeLength += accountValueBefore.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 15)) {
			accountValueAfter = new MoneyAmount();
			subCodeLength += accountValueAfter.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 16)) {
			sessionID = new SessionID();
			subCodeLength += sessionID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 17)) {
			userName = new UserName();
			subCodeLength += userName.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 18)) {
			numberOfSDPInterrogations = new NumberOfSDPInterrogations();
			subCodeLength += numberOfSDPInterrogations.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 19)) {
			originRealm = new OriginRealm();
			subCodeLength += originRealm.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 20)) {
			originHost = new OriginHost();
			subCodeLength += originHost.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 21)) {
			serviceClass = new ServiceClass();
			subCodeLength += serviceClass.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 22)) {
			accountNumber = new AddressString();
			subCodeLength += accountNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 23)) {
			localSequenceNumber = new LocalSequenceNumber();
			subCodeLength += localSequenceNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 24)) {
			familyAndFriendsIndicator = new FamilyAndFriendsIndicator();
			subCodeLength += familyAndFriendsIndicator.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 25)) {
			currencyType = new CurrencyType();
			subCodeLength += currencyType.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 26)) {
			accumulatorValueInfo = new AccumulatorValueInfo();
			subCodeLength += accumulatorValueInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 27)) {
			dedicatedAccountInfo = new DedicatedAccountInfo();
			subCodeLength += dedicatedAccountInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 28)) {
			serviceProviderID = new ServiceProviderID();
			subCodeLength += serviceProviderID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 29)) {
			extInt1 = new ExtInt();
			subCodeLength += extInt1.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 30)) {
			extInt2 = new ExtInt();
			subCodeLength += extInt2.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 31)) {
			extInt3 = new ExtInt();
			subCodeLength += extInt3.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 32)) {
			extInt4 = new ExtInt();
			subCodeLength += extInt4.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 33)) {
			extText = new ExtText();
			subCodeLength += extText.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 34)) {
			gprsQoS = new GPRSQoS();
			subCodeLength += gprsQoS.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 35)) {
			redirectingPartyNumber = new AddressString();
			subCodeLength += redirectingPartyNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 36)) {
			originatingLocationInfo = new AddressString();
			subCodeLength += originatingLocationInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 37)) {
			terminatingLocationInfo = new AddressString();
			subCodeLength += terminatingLocationInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 38)) {
			networkID = new NetworkID();
			subCodeLength += networkID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 39)) {
			subscriptionType = new SubscriptionType();
			subCodeLength += subscriptionType.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 40)) {
			smsDeliveryStatus = new SmsDeliveryStatus();
			subCodeLength += smsDeliveryStatus.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 41)) {
			calledPartyNumber2 = new AddressString();
			subCodeLength += calledPartyNumber2.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 42)) {
			calledPartyNumber3 = new AddressString();
			subCodeLength += calledPartyNumber3.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 43)) {
			radiusSessionID = new RadiusSessionID();
			subCodeLength += radiusSessionID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 44)) {
			multiSessionID = new MultiSessionID();
			subCodeLength += multiSessionID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 45)) {
			originalSubscriptionIDData = new SubscriptionIDData();
			subCodeLength += originalSubscriptionIDData.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 46)) {
			originalSubscriptionIDType = new SubscriptionIDType();
			subCodeLength += originalSubscriptionIDType.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 47)) {
			accountingCorrelationID = new AccountingCorrelationID();
			subCodeLength += accountingCorrelationID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 48)) {
			abnormalTerminationReason = new AbnormalTerminationReason();
			subCodeLength += abnormalTerminationReason.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 49)) {
			accountGroupID = new AccountGroupID();
			subCodeLength += accountGroupID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 50)) {
			serviceOfferings = new ServiceOfferings();
			subCodeLength += serviceOfferings.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 51)) {
			communityDataInfo = new CommunityDataInfo();
			subCodeLength += communityDataInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 52)) {
			usedAmountLastInterval = new MoneyAmount();
			subCodeLength += usedAmountLastInterval.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 53)) {
			deductedAmountLastInterval = new MoneyAmount();
			subCodeLength += deductedAmountLastInterval.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 54)) {
			categorizationInformation = new CategorizationInformation();
			subCodeLength += categorizationInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 55)) {
			ratedDurations = new RatedDurations();
			subCodeLength += ratedDurations.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (cdrReason != null) {
			sb.append("cdrReason: ").append(cdrReason);
		}
		else {
			sb.append("cdrReason: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (nodeID != null) {
			sb.append("nodeID: ").append(nodeID);
		}
		else {
			sb.append("nodeID: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (recordSequenceNumber != null) {
			sb.append("recordSequenceNumber: ").append(recordSequenceNumber);
		}
		else {
			sb.append("recordSequenceNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (lastPartialOutput != null) {
			sb.append("lastPartialOutput: ").append(lastPartialOutput);
		}
		else {
			sb.append("lastPartialOutput: <empty-required-field>");
		}
		
		if (trafficCase != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trafficCase: ").append(trafficCase);
		}
		
		if (teleServiceCode != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("teleServiceCode: ").append(teleServiceCode);
		}
		
		if (subscriberID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("subscriberID: ").append(subscriberID);
		}
		
		if (callingPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callingPartyNumber: ").append(callingPartyNumber);
		}
		
		if (calledPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber: ").append(calledPartyNumber);
		}
		
		if (triggerTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("triggerTime: ").append(triggerTime);
		}
		
		if (chargedDuration != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedDuration: ").append(chargedDuration);
		}
		
		if (dataVolume != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("dataVolume: ").append(dataVolume);
		}
		
		if (numberOfEvents != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("numberOfEvents: ").append(numberOfEvents);
		}
		
		if (finalCharge != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("finalCharge: ").append(finalCharge);
		}
		
		if (accountValueBefore != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueBefore: ").append(accountValueBefore);
		}
		
		if (accountValueAfter != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueAfter: ").append(accountValueAfter);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (sessionID != null) {
			sb.append("sessionID: ").append(sessionID);
		}
		else {
			sb.append("sessionID: <empty-required-field>");
		}
		
		if (userName != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("userName: ").append(userName);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (numberOfSDPInterrogations != null) {
			sb.append("numberOfSDPInterrogations: ").append(numberOfSDPInterrogations);
		}
		else {
			sb.append("numberOfSDPInterrogations: <empty-required-field>");
		}
		
		if (originRealm != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originRealm: ").append(originRealm);
		}
		
		if (originHost != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originHost: ").append(originHost);
		}
		
		if (serviceClass != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceClass: ").append(serviceClass);
		}
		
		if (accountNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountNumber: ").append(accountNumber);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (localSequenceNumber != null) {
			sb.append("localSequenceNumber: ").append(localSequenceNumber);
		}
		else {
			sb.append("localSequenceNumber: <empty-required-field>");
		}
		
		if (familyAndFriendsIndicator != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("familyAndFriendsIndicator: ").append(familyAndFriendsIndicator);
		}
		
		if (currencyType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("currencyType: ").append(currencyType);
		}
		
		if (accumulatorValueInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accumulatorValueInfo: ");
			accumulatorValueInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (dedicatedAccountInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("dedicatedAccountInfo: ");
			dedicatedAccountInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (serviceProviderID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceProviderID: ").append(serviceProviderID);
		}
		
		if (extInt1 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extInt1: ").append(extInt1);
		}
		
		if (extInt2 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extInt2: ").append(extInt2);
		}
		
		if (extInt3 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extInt3: ").append(extInt3);
		}
		
		if (extInt4 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extInt4: ").append(extInt4);
		}
		
		if (extText != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("extText: ").append(extText);
		}
		
		if (gprsQoS != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("gprsQoS: ").append(gprsQoS);
		}
		
		if (redirectingPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("redirectingPartyNumber: ").append(redirectingPartyNumber);
		}
		
		if (originatingLocationInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originatingLocationInfo: ").append(originatingLocationInfo);
		}
		
		if (terminatingLocationInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("terminatingLocationInfo: ").append(terminatingLocationInfo);
		}
		
		if (networkID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkID: ").append(networkID);
		}
		
		if (subscriptionType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("subscriptionType: ").append(subscriptionType);
		}
		
		if (smsDeliveryStatus != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("smsDeliveryStatus: ").append(smsDeliveryStatus);
		}
		
		if (calledPartyNumber2 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber2: ").append(calledPartyNumber2);
		}
		
		if (calledPartyNumber3 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber3: ").append(calledPartyNumber3);
		}
		
		if (radiusSessionID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("radiusSessionID: ").append(radiusSessionID);
		}
		
		if (multiSessionID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("multiSessionID: ").append(multiSessionID);
		}
		
		if (originalSubscriptionIDData != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originalSubscriptionIDData: ").append(originalSubscriptionIDData);
		}
		
		if (originalSubscriptionIDType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originalSubscriptionIDType: ").append(originalSubscriptionIDType);
		}
		
		if (accountingCorrelationID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountingCorrelationID: ").append(accountingCorrelationID);
		}
		
		if (abnormalTerminationReason != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("abnormalTerminationReason: ").append(abnormalTerminationReason);
		}
		
		if (accountGroupID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountGroupID: ").append(accountGroupID);
		}
		
		if (serviceOfferings != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceOfferings: ").append(serviceOfferings);
		}
		
		if (communityDataInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("communityDataInfo: ");
			communityDataInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (usedAmountLastInterval != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("usedAmountLastInterval: ").append(usedAmountLastInterval);
		}
		
		if (deductedAmountLastInterval != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("deductedAmountLastInterval: ").append(deductedAmountLastInterval);
		}
		
		if (categorizationInformation != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("categorizationInformation: ");
			categorizationInformation.appendAsString(sb, indentLevel + 1);
		}
		
		if (ratedDurations != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ratedDurations: ");
			ratedDurations.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

