/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package chargingcdr;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class IndividualPriceFactorHistory implements Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private IndividualPriceFactor individualPriceFactor1 = null;
	private IndividualPriceFactor individualPriceFactor2 = null;
	private Units individualPriceFactor1Units = null;
	
	public IndividualPriceFactorHistory() {
	}

	public IndividualPriceFactorHistory(byte[] code) {
		this.code = code;
	}

	public void setIndividualPriceFactor1(IndividualPriceFactor individualPriceFactor1) {
		this.individualPriceFactor1 = individualPriceFactor1;
	}

	public IndividualPriceFactor getIndividualPriceFactor1() {
		return individualPriceFactor1;
	}

	public void setIndividualPriceFactor2(IndividualPriceFactor individualPriceFactor2) {
		this.individualPriceFactor2 = individualPriceFactor2;
	}

	public IndividualPriceFactor getIndividualPriceFactor2() {
		return individualPriceFactor2;
	}

	public void setIndividualPriceFactor1Units(Units individualPriceFactor1Units) {
		this.individualPriceFactor1Units = individualPriceFactor1Units;
	}

	public Units getIndividualPriceFactor1Units() {
		return individualPriceFactor1Units;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (individualPriceFactor1Units != null) {
			codeLength += individualPriceFactor1Units.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 2
			os.write(0xA2);
			codeLength += 1;
		}
		
		if (individualPriceFactor2 != null) {
			codeLength += individualPriceFactor2.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			os.write(0x81);
			codeLength += 1;
		}
		
		if (individualPriceFactor1 != null) {
			codeLength += individualPriceFactor1.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			os.write(0x80);
			codeLength += 1;
		}
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			individualPriceFactor1 = new IndividualPriceFactor();
			subCodeLength += individualPriceFactor1.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			individualPriceFactor2 = new IndividualPriceFactor();
			subCodeLength += individualPriceFactor2.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 2)) {
			individualPriceFactor1Units = new Units();
			subCodeLength += individualPriceFactor1Units.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (individualPriceFactor1 != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("individualPriceFactor1: ").append(individualPriceFactor1);
			firstSelectedElement = false;
		}
		
		if (individualPriceFactor2 != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("individualPriceFactor2: ").append(individualPriceFactor2);
			firstSelectedElement = false;
		}
		
		if (individualPriceFactor1Units != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("individualPriceFactor1Units: ");
			individualPriceFactor1Units.appendAsString(sb, indentLevel + 1);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

