/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package chargingcdr;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class RTCCreditControlRecord implements Serializable {

	private static final long serialVersionUID = 1L;

	public static class AccumulatorValueInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.AccumulatorValueInfo> seqOf = null;

		public AccumulatorValueInfo() {
			seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
		}

		public AccumulatorValueInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.AccumulatorValueInfo> getAccumulatorValueInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.AccumulatorValueInfo element = new chargingcdr.AccumulatorValueInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.AccumulatorValueInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class DedicatedAccountInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.DedicatedAccountInfo> seqOf = null;

		public DedicatedAccountInfo() {
			seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
		}

		public DedicatedAccountInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.DedicatedAccountInfo> getDedicatedAccountInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.DedicatedAccountInfo element = new chargingcdr.DedicatedAccountInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.DedicatedAccountInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class CommunityDataInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.CommunityDataInfo> seqOf = null;

		public CommunityDataInfo() {
			seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
		}

		public CommunityDataInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.CommunityDataInfo> getCommunityDataInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.CommunityDataInfo element = new chargingcdr.CommunityDataInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.CommunityDataInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private CdrReason cdrReason = null;
	private NodeID nodeID = null;
	private RecordSequenceNumber recordSequenceNumber = null;
	private BerBoolean lastPartialOutput = null;
	private TrafficCase trafficCase = null;
	private TeleServiceCode teleServiceCode = null;
	private AddressString subscriberID = null;
	private AddressString callingPartyNumber = null;
	private AddressString calledPartyNumber = null;
	private TimeStamp triggerTime = null;
	private ChargedDuration chargedDuration = null;
	private IMSI servedIMSI = null;
	private NumberOfEvents numberOfEvents = null;
	private MoneyAmount finalCharge = null;
	private MoneyAmount accountValueBefore = null;
	private MoneyAmount accountValueAfter = null;
	private AccountingCorrelationID accountingCorrelationID = null;
	private NumberOfSDPInterrogations numberOfSDPInterrogations = null;
	private ServiceClass serviceClass = null;
	private AddressString accountNumber = null;
	private LocalSequenceNumber localSequenceNumber = null;
	private FamilyAndFriendsIndicator familyAndFriendsIndicator = null;
	private CurrencyType currencyType = null;
	private AccumulatorValueInfo accumulatorValueInfo = null;
	private DedicatedAccountInfo dedicatedAccountInfo = null;
	private AddressString redirectingPartyNumber = null;
	private AddressString originatingLocationInfo = null;
	private AddressString terminatingLocationInfo = null;
	private NetworkID networkID = null;
	private SubscriptionType subscriptionType = null;
	private AddressString calledPartyNumber2 = null;
	private AddressString calledPartyNumber3 = null;
	private AccountGroupID accountGroupID = null;
	private ServiceOfferings serviceOfferings = null;
	private CommunityDataInfo communityDataInfo = null;
	private AddressString serviceCenter = null;
	private TimeStamp startOfCharging = null;
	private CallSetUpResultCode callSetUpResultCode = null;
	private UsedUnchargedDuration usedUnchargedDuration = null;
	private UsedUnchargedEvent usedUnchargedEvent = null;
	private CategorizationInformation categorizationInformation = null;
	private RatedDurations ratedDurations = null;
	private IndividualPriceFactorHistory individualPriceFactorHistory = null;
	
	public RTCCreditControlRecord() {
	}

	public RTCCreditControlRecord(byte[] code) {
		this.code = code;
	}

	public void setCdrReason(CdrReason cdrReason) {
		this.cdrReason = cdrReason;
	}

	public CdrReason getCdrReason() {
		return cdrReason;
	}

	public void setNodeID(NodeID nodeID) {
		this.nodeID = nodeID;
	}

	public NodeID getNodeID() {
		return nodeID;
	}

	public void setRecordSequenceNumber(RecordSequenceNumber recordSequenceNumber) {
		this.recordSequenceNumber = recordSequenceNumber;
	}

	public RecordSequenceNumber getRecordSequenceNumber() {
		return recordSequenceNumber;
	}

	public void setLastPartialOutput(BerBoolean lastPartialOutput) {
		this.lastPartialOutput = lastPartialOutput;
	}

	public BerBoolean getLastPartialOutput() {
		return lastPartialOutput;
	}

	public void setTrafficCase(TrafficCase trafficCase) {
		this.trafficCase = trafficCase;
	}

	public TrafficCase getTrafficCase() {
		return trafficCase;
	}

	public void setTeleServiceCode(TeleServiceCode teleServiceCode) {
		this.teleServiceCode = teleServiceCode;
	}

	public TeleServiceCode getTeleServiceCode() {
		return teleServiceCode;
	}

	public void setSubscriberID(AddressString subscriberID) {
		this.subscriberID = subscriberID;
	}

	public AddressString getSubscriberID() {
		return subscriberID;
	}

	public void setCallingPartyNumber(AddressString callingPartyNumber) {
		this.callingPartyNumber = callingPartyNumber;
	}

	public AddressString getCallingPartyNumber() {
		return callingPartyNumber;
	}

	public void setCalledPartyNumber(AddressString calledPartyNumber) {
		this.calledPartyNumber = calledPartyNumber;
	}

	public AddressString getCalledPartyNumber() {
		return calledPartyNumber;
	}

	public void setTriggerTime(TimeStamp triggerTime) {
		this.triggerTime = triggerTime;
	}

	public TimeStamp getTriggerTime() {
		return triggerTime;
	}

	public void setChargedDuration(ChargedDuration chargedDuration) {
		this.chargedDuration = chargedDuration;
	}

	public ChargedDuration getChargedDuration() {
		return chargedDuration;
	}

	public void setServedIMSI(IMSI servedIMSI) {
		this.servedIMSI = servedIMSI;
	}

	public IMSI getServedIMSI() {
		return servedIMSI;
	}

	public void setNumberOfEvents(NumberOfEvents numberOfEvents) {
		this.numberOfEvents = numberOfEvents;
	}

	public NumberOfEvents getNumberOfEvents() {
		return numberOfEvents;
	}

	public void setFinalCharge(MoneyAmount finalCharge) {
		this.finalCharge = finalCharge;
	}

	public MoneyAmount getFinalCharge() {
		return finalCharge;
	}

	public void setAccountValueBefore(MoneyAmount accountValueBefore) {
		this.accountValueBefore = accountValueBefore;
	}

	public MoneyAmount getAccountValueBefore() {
		return accountValueBefore;
	}

	public void setAccountValueAfter(MoneyAmount accountValueAfter) {
		this.accountValueAfter = accountValueAfter;
	}

	public MoneyAmount getAccountValueAfter() {
		return accountValueAfter;
	}

	public void setAccountingCorrelationID(AccountingCorrelationID accountingCorrelationID) {
		this.accountingCorrelationID = accountingCorrelationID;
	}

	public AccountingCorrelationID getAccountingCorrelationID() {
		return accountingCorrelationID;
	}

	public void setNumberOfSDPInterrogations(NumberOfSDPInterrogations numberOfSDPInterrogations) {
		this.numberOfSDPInterrogations = numberOfSDPInterrogations;
	}

	public NumberOfSDPInterrogations getNumberOfSDPInterrogations() {
		return numberOfSDPInterrogations;
	}

	public void setServiceClass(ServiceClass serviceClass) {
		this.serviceClass = serviceClass;
	}

	public ServiceClass getServiceClass() {
		return serviceClass;
	}

	public void setAccountNumber(AddressString accountNumber) {
		this.accountNumber = accountNumber;
	}

	public AddressString getAccountNumber() {
		return accountNumber;
	}

	public void setLocalSequenceNumber(LocalSequenceNumber localSequenceNumber) {
		this.localSequenceNumber = localSequenceNumber;
	}

	public LocalSequenceNumber getLocalSequenceNumber() {
		return localSequenceNumber;
	}

	public void setFamilyAndFriendsIndicator(FamilyAndFriendsIndicator familyAndFriendsIndicator) {
		this.familyAndFriendsIndicator = familyAndFriendsIndicator;
	}

	public FamilyAndFriendsIndicator getFamilyAndFriendsIndicator() {
		return familyAndFriendsIndicator;
	}

	public void setCurrencyType(CurrencyType currencyType) {
		this.currencyType = currencyType;
	}

	public CurrencyType getCurrencyType() {
		return currencyType;
	}

	public void setAccumulatorValueInfo(AccumulatorValueInfo accumulatorValueInfo) {
		this.accumulatorValueInfo = accumulatorValueInfo;
	}

	public AccumulatorValueInfo getAccumulatorValueInfo() {
		return accumulatorValueInfo;
	}

	public void setDedicatedAccountInfo(DedicatedAccountInfo dedicatedAccountInfo) {
		this.dedicatedAccountInfo = dedicatedAccountInfo;
	}

	public DedicatedAccountInfo getDedicatedAccountInfo() {
		return dedicatedAccountInfo;
	}

	public void setRedirectingPartyNumber(AddressString redirectingPartyNumber) {
		this.redirectingPartyNumber = redirectingPartyNumber;
	}

	public AddressString getRedirectingPartyNumber() {
		return redirectingPartyNumber;
	}

	public void setOriginatingLocationInfo(AddressString originatingLocationInfo) {
		this.originatingLocationInfo = originatingLocationInfo;
	}

	public AddressString getOriginatingLocationInfo() {
		return originatingLocationInfo;
	}

	public void setTerminatingLocationInfo(AddressString terminatingLocationInfo) {
		this.terminatingLocationInfo = terminatingLocationInfo;
	}

	public AddressString getTerminatingLocationInfo() {
		return terminatingLocationInfo;
	}

	public void setNetworkID(NetworkID networkID) {
		this.networkID = networkID;
	}

	public NetworkID getNetworkID() {
		return networkID;
	}

	public void setSubscriptionType(SubscriptionType subscriptionType) {
		this.subscriptionType = subscriptionType;
	}

	public SubscriptionType getSubscriptionType() {
		return subscriptionType;
	}

	public void setCalledPartyNumber2(AddressString calledPartyNumber2) {
		this.calledPartyNumber2 = calledPartyNumber2;
	}

	public AddressString getCalledPartyNumber2() {
		return calledPartyNumber2;
	}

	public void setCalledPartyNumber3(AddressString calledPartyNumber3) {
		this.calledPartyNumber3 = calledPartyNumber3;
	}

	public AddressString getCalledPartyNumber3() {
		return calledPartyNumber3;
	}

	public void setAccountGroupID(AccountGroupID accountGroupID) {
		this.accountGroupID = accountGroupID;
	}

	public AccountGroupID getAccountGroupID() {
		return accountGroupID;
	}

	public void setServiceOfferings(ServiceOfferings serviceOfferings) {
		this.serviceOfferings = serviceOfferings;
	}

	public ServiceOfferings getServiceOfferings() {
		return serviceOfferings;
	}

	public void setCommunityDataInfo(CommunityDataInfo communityDataInfo) {
		this.communityDataInfo = communityDataInfo;
	}

	public CommunityDataInfo getCommunityDataInfo() {
		return communityDataInfo;
	}

	public void setServiceCenter(AddressString serviceCenter) {
		this.serviceCenter = serviceCenter;
	}

	public AddressString getServiceCenter() {
		return serviceCenter;
	}

	public void setStartOfCharging(TimeStamp startOfCharging) {
		this.startOfCharging = startOfCharging;
	}

	public TimeStamp getStartOfCharging() {
		return startOfCharging;
	}

	public void setCallSetUpResultCode(CallSetUpResultCode callSetUpResultCode) {
		this.callSetUpResultCode = callSetUpResultCode;
	}

	public CallSetUpResultCode getCallSetUpResultCode() {
		return callSetUpResultCode;
	}

	public void setUsedUnchargedDuration(UsedUnchargedDuration usedUnchargedDuration) {
		this.usedUnchargedDuration = usedUnchargedDuration;
	}

	public UsedUnchargedDuration getUsedUnchargedDuration() {
		return usedUnchargedDuration;
	}

	public void setUsedUnchargedEvent(UsedUnchargedEvent usedUnchargedEvent) {
		this.usedUnchargedEvent = usedUnchargedEvent;
	}

	public UsedUnchargedEvent getUsedUnchargedEvent() {
		return usedUnchargedEvent;
	}

	public void setCategorizationInformation(CategorizationInformation categorizationInformation) {
		this.categorizationInformation = categorizationInformation;
	}

	public CategorizationInformation getCategorizationInformation() {
		return categorizationInformation;
	}

	public void setRatedDurations(RatedDurations ratedDurations) {
		this.ratedDurations = ratedDurations;
	}

	public RatedDurations getRatedDurations() {
		return ratedDurations;
	}

	public void setIndividualPriceFactorHistory(IndividualPriceFactorHistory individualPriceFactorHistory) {
		this.individualPriceFactorHistory = individualPriceFactorHistory;
	}

	public IndividualPriceFactorHistory getIndividualPriceFactorHistory() {
		return individualPriceFactorHistory;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (individualPriceFactorHistory != null) {
			codeLength += individualPriceFactorHistory.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 42
			os.write(0x2A);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (ratedDurations != null) {
			codeLength += ratedDurations.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 41
			os.write(0x29);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (categorizationInformation != null) {
			codeLength += categorizationInformation.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 40
			os.write(0x28);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (usedUnchargedEvent != null) {
			codeLength += usedUnchargedEvent.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 39
			os.write(0x27);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (usedUnchargedDuration != null) {
			codeLength += usedUnchargedDuration.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 38
			os.write(0x26);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (callSetUpResultCode != null) {
			codeLength += callSetUpResultCode.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 37
			os.write(0x25);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (startOfCharging != null) {
			codeLength += startOfCharging.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 36
			os.write(0x24);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (serviceCenter != null) {
			codeLength += serviceCenter.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 35
			os.write(0x23);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (communityDataInfo != null) {
			codeLength += communityDataInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 34
			os.write(0x22);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (serviceOfferings != null) {
			codeLength += serviceOfferings.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 33
			os.write(0x21);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (accountGroupID != null) {
			codeLength += accountGroupID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 32
			os.write(0x20);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (calledPartyNumber3 != null) {
			codeLength += calledPartyNumber3.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 31
			os.write(0x1F);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (calledPartyNumber2 != null) {
			codeLength += calledPartyNumber2.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 30
			os.write(0x9E);
			codeLength += 1;
		}
		
		if (subscriptionType != null) {
			codeLength += subscriptionType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 29
			os.write(0x9D);
			codeLength += 1;
		}
		
		if (networkID != null) {
			codeLength += networkID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 28
			os.write(0x9C);
			codeLength += 1;
		}
		
		if (terminatingLocationInfo != null) {
			codeLength += terminatingLocationInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 27
			os.write(0x9B);
			codeLength += 1;
		}
		
		if (originatingLocationInfo != null) {
			codeLength += originatingLocationInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 26
			os.write(0x9A);
			codeLength += 1;
		}
		
		if (redirectingPartyNumber != null) {
			codeLength += redirectingPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 25
			os.write(0x99);
			codeLength += 1;
		}
		
		if (dedicatedAccountInfo != null) {
			codeLength += dedicatedAccountInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 24
			os.write(0xB8);
			codeLength += 1;
		}
		
		if (accumulatorValueInfo != null) {
			codeLength += accumulatorValueInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 23
			os.write(0xB7);
			codeLength += 1;
		}
		
		if (currencyType != null) {
			codeLength += currencyType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 22
			os.write(0x96);
			codeLength += 1;
		}
		
		if (familyAndFriendsIndicator != null) {
			codeLength += familyAndFriendsIndicator.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 21
			os.write(0x95);
			codeLength += 1;
		}
		
		codeLength += localSequenceNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 20
		os.write(0x94);
		codeLength += 1;
		
		if (accountNumber != null) {
			codeLength += accountNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 19
			os.write(0x93);
			codeLength += 1;
		}
		
		if (serviceClass != null) {
			codeLength += serviceClass.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 18
			os.write(0x92);
			codeLength += 1;
		}
		
		codeLength += numberOfSDPInterrogations.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 17
		os.write(0x91);
		codeLength += 1;
		
		codeLength += accountingCorrelationID.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 16
		os.write(0x90);
		codeLength += 1;
		
		if (accountValueAfter != null) {
			codeLength += accountValueAfter.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 15
			os.write(0x8F);
			codeLength += 1;
		}
		
		if (accountValueBefore != null) {
			codeLength += accountValueBefore.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 14
			os.write(0x8E);
			codeLength += 1;
		}
		
		if (finalCharge != null) {
			codeLength += finalCharge.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 13
			os.write(0x8D);
			codeLength += 1;
		}
		
		if (numberOfEvents != null) {
			codeLength += numberOfEvents.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 12
			os.write(0x8C);
			codeLength += 1;
		}
		
		if (servedIMSI != null) {
			codeLength += servedIMSI.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 11
			os.write(0x8B);
			codeLength += 1;
		}
		
		if (chargedDuration != null) {
			codeLength += chargedDuration.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 10
			os.write(0x8A);
			codeLength += 1;
		}
		
		if (triggerTime != null) {
			codeLength += triggerTime.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 9
			os.write(0x89);
			codeLength += 1;
		}
		
		if (calledPartyNumber != null) {
			codeLength += calledPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 8
			os.write(0x88);
			codeLength += 1;
		}
		
		if (callingPartyNumber != null) {
			codeLength += callingPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 7
			os.write(0x87);
			codeLength += 1;
		}
		
		if (subscriberID != null) {
			codeLength += subscriberID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 6
			os.write(0x86);
			codeLength += 1;
		}
		
		if (teleServiceCode != null) {
			codeLength += teleServiceCode.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 5
			os.write(0x85);
			codeLength += 1;
		}
		
		if (trafficCase != null) {
			codeLength += trafficCase.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 4
			os.write(0x84);
			codeLength += 1;
		}
		
		codeLength += lastPartialOutput.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 3
		os.write(0x83);
		codeLength += 1;
		
		codeLength += recordSequenceNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		os.write(0x82);
		codeLength += 1;
		
		codeLength += nodeID.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		os.write(0x81);
		codeLength += 1;
		
		codeLength += cdrReason.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		os.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			cdrReason = new CdrReason();
			subCodeLength += cdrReason.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			nodeID = new NodeID();
			subCodeLength += nodeID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			recordSequenceNumber = new RecordSequenceNumber();
			subCodeLength += recordSequenceNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			lastPartialOutput = new BerBoolean();
			subCodeLength += lastPartialOutput.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			trafficCase = new TrafficCase();
			subCodeLength += trafficCase.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			teleServiceCode = new TeleServiceCode();
			subCodeLength += teleServiceCode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 6)) {
			subscriberID = new AddressString();
			subCodeLength += subscriberID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 7)) {
			callingPartyNumber = new AddressString();
			subCodeLength += callingPartyNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 8)) {
			calledPartyNumber = new AddressString();
			subCodeLength += calledPartyNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 9)) {
			triggerTime = new TimeStamp();
			subCodeLength += triggerTime.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 10)) {
			chargedDuration = new ChargedDuration();
			subCodeLength += chargedDuration.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 11)) {
			servedIMSI = new IMSI();
			subCodeLength += servedIMSI.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 12)) {
			numberOfEvents = new NumberOfEvents();
			subCodeLength += numberOfEvents.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 13)) {
			finalCharge = new MoneyAmount();
			subCodeLength += finalCharge.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 14)) {
			accountValueBefore = new MoneyAmount();
			subCodeLength += accountValueBefore.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 15)) {
			accountValueAfter = new MoneyAmount();
			subCodeLength += accountValueAfter.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 16)) {
			accountingCorrelationID = new AccountingCorrelationID();
			subCodeLength += accountingCorrelationID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 17)) {
			numberOfSDPInterrogations = new NumberOfSDPInterrogations();
			subCodeLength += numberOfSDPInterrogations.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 18)) {
			serviceClass = new ServiceClass();
			subCodeLength += serviceClass.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 19)) {
			accountNumber = new AddressString();
			subCodeLength += accountNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 20)) {
			localSequenceNumber = new LocalSequenceNumber();
			subCodeLength += localSequenceNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 21)) {
			familyAndFriendsIndicator = new FamilyAndFriendsIndicator();
			subCodeLength += familyAndFriendsIndicator.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 22)) {
			currencyType = new CurrencyType();
			subCodeLength += currencyType.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 23)) {
			accumulatorValueInfo = new AccumulatorValueInfo();
			subCodeLength += accumulatorValueInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 24)) {
			dedicatedAccountInfo = new DedicatedAccountInfo();
			subCodeLength += dedicatedAccountInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 25)) {
			redirectingPartyNumber = new AddressString();
			subCodeLength += redirectingPartyNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 26)) {
			originatingLocationInfo = new AddressString();
			subCodeLength += originatingLocationInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 27)) {
			terminatingLocationInfo = new AddressString();
			subCodeLength += terminatingLocationInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 28)) {
			networkID = new NetworkID();
			subCodeLength += networkID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 29)) {
			subscriptionType = new SubscriptionType();
			subCodeLength += subscriptionType.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 30)) {
			calledPartyNumber2 = new AddressString();
			subCodeLength += calledPartyNumber2.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 31)) {
			calledPartyNumber3 = new AddressString();
			subCodeLength += calledPartyNumber3.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 32)) {
			accountGroupID = new AccountGroupID();
			subCodeLength += accountGroupID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 33)) {
			serviceOfferings = new ServiceOfferings();
			subCodeLength += serviceOfferings.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 34)) {
			communityDataInfo = new CommunityDataInfo();
			subCodeLength += communityDataInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 35)) {
			serviceCenter = new AddressString();
			subCodeLength += serviceCenter.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 36)) {
			startOfCharging = new TimeStamp();
			subCodeLength += startOfCharging.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 37)) {
			callSetUpResultCode = new CallSetUpResultCode();
			subCodeLength += callSetUpResultCode.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 38)) {
			usedUnchargedDuration = new UsedUnchargedDuration();
			subCodeLength += usedUnchargedDuration.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 39)) {
			usedUnchargedEvent = new UsedUnchargedEvent();
			subCodeLength += usedUnchargedEvent.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 40)) {
			categorizationInformation = new CategorizationInformation();
			subCodeLength += categorizationInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 41)) {
			ratedDurations = new RatedDurations();
			subCodeLength += ratedDurations.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 42)) {
			individualPriceFactorHistory = new IndividualPriceFactorHistory();
			subCodeLength += individualPriceFactorHistory.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (cdrReason != null) {
			sb.append("cdrReason: ").append(cdrReason);
		}
		else {
			sb.append("cdrReason: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (nodeID != null) {
			sb.append("nodeID: ").append(nodeID);
		}
		else {
			sb.append("nodeID: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (recordSequenceNumber != null) {
			sb.append("recordSequenceNumber: ").append(recordSequenceNumber);
		}
		else {
			sb.append("recordSequenceNumber: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (lastPartialOutput != null) {
			sb.append("lastPartialOutput: ").append(lastPartialOutput);
		}
		else {
			sb.append("lastPartialOutput: <empty-required-field>");
		}
		
		if (trafficCase != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trafficCase: ").append(trafficCase);
		}
		
		if (teleServiceCode != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("teleServiceCode: ").append(teleServiceCode);
		}
		
		if (subscriberID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("subscriberID: ").append(subscriberID);
		}
		
		if (callingPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callingPartyNumber: ").append(callingPartyNumber);
		}
		
		if (calledPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber: ").append(calledPartyNumber);
		}
		
		if (triggerTime != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("triggerTime: ").append(triggerTime);
		}
		
		if (chargedDuration != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("chargedDuration: ").append(chargedDuration);
		}
		
		if (servedIMSI != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("servedIMSI: ").append(servedIMSI);
		}
		
		if (numberOfEvents != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("numberOfEvents: ").append(numberOfEvents);
		}
		
		if (finalCharge != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("finalCharge: ").append(finalCharge);
		}
		
		if (accountValueBefore != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueBefore: ").append(accountValueBefore);
		}
		
		if (accountValueAfter != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueAfter: ").append(accountValueAfter);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (accountingCorrelationID != null) {
			sb.append("accountingCorrelationID: ").append(accountingCorrelationID);
		}
		else {
			sb.append("accountingCorrelationID: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (numberOfSDPInterrogations != null) {
			sb.append("numberOfSDPInterrogations: ").append(numberOfSDPInterrogations);
		}
		else {
			sb.append("numberOfSDPInterrogations: <empty-required-field>");
		}
		
		if (serviceClass != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceClass: ").append(serviceClass);
		}
		
		if (accountNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountNumber: ").append(accountNumber);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (localSequenceNumber != null) {
			sb.append("localSequenceNumber: ").append(localSequenceNumber);
		}
		else {
			sb.append("localSequenceNumber: <empty-required-field>");
		}
		
		if (familyAndFriendsIndicator != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("familyAndFriendsIndicator: ").append(familyAndFriendsIndicator);
		}
		
		if (currencyType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("currencyType: ").append(currencyType);
		}
		
		if (accumulatorValueInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accumulatorValueInfo: ");
			accumulatorValueInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (dedicatedAccountInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("dedicatedAccountInfo: ");
			dedicatedAccountInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (redirectingPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("redirectingPartyNumber: ").append(redirectingPartyNumber);
		}
		
		if (originatingLocationInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originatingLocationInfo: ").append(originatingLocationInfo);
		}
		
		if (terminatingLocationInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("terminatingLocationInfo: ").append(terminatingLocationInfo);
		}
		
		if (networkID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkID: ").append(networkID);
		}
		
		if (subscriptionType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("subscriptionType: ").append(subscriptionType);
		}
		
		if (calledPartyNumber2 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber2: ").append(calledPartyNumber2);
		}
		
		if (calledPartyNumber3 != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber3: ").append(calledPartyNumber3);
		}
		
		if (accountGroupID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountGroupID: ").append(accountGroupID);
		}
		
		if (serviceOfferings != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceOfferings: ").append(serviceOfferings);
		}
		
		if (communityDataInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("communityDataInfo: ");
			communityDataInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (serviceCenter != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceCenter: ").append(serviceCenter);
		}
		
		if (startOfCharging != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("startOfCharging: ").append(startOfCharging);
		}
		
		if (callSetUpResultCode != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("callSetUpResultCode: ").append(callSetUpResultCode);
		}
		
		if (usedUnchargedDuration != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("usedUnchargedDuration: ").append(usedUnchargedDuration);
		}
		
		if (usedUnchargedEvent != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("usedUnchargedEvent: ").append(usedUnchargedEvent);
		}
		
		if (categorizationInformation != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("categorizationInformation: ");
			categorizationInformation.appendAsString(sb, indentLevel + 1);
		}
		
		if (ratedDurations != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ratedDurations: ");
			ratedDurations.appendAsString(sb, indentLevel + 1);
		}
		
		if (individualPriceFactorHistory != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("individualPriceFactorHistory: ");
			individualPriceFactorHistory.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

