/**
 * This class file was automatically generated by jASN1 v1.9.0 (http://www.openmuc.org)
 */

package chargingcdr;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class SCFSMSMORecord implements Serializable {

	private static final long serialVersionUID = 1L;

	public static class AccumulatorValueInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.AccumulatorValueInfo> seqOf = null;

		public AccumulatorValueInfo() {
			seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
		}

		public AccumulatorValueInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.AccumulatorValueInfo> getAccumulatorValueInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.AccumulatorValueInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.AccumulatorValueInfo element = new chargingcdr.AccumulatorValueInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.AccumulatorValueInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class DedicatedAccountInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.DedicatedAccountInfo> seqOf = null;

		public DedicatedAccountInfo() {
			seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
		}

		public DedicatedAccountInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.DedicatedAccountInfo> getDedicatedAccountInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.DedicatedAccountInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.DedicatedAccountInfo element = new chargingcdr.DedicatedAccountInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.DedicatedAccountInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static class CommunityDataInfo implements Serializable {

		private static final long serialVersionUID = 1L;

		public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);
		public byte[] code = null;
		private List<chargingcdr.CommunityDataInfo> seqOf = null;

		public CommunityDataInfo() {
			seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
		}

		public CommunityDataInfo(byte[] code) {
			this.code = code;
		}

		public List<chargingcdr.CommunityDataInfo> getCommunityDataInfo() {
			if (seqOf == null) {
				seqOf = new ArrayList<chargingcdr.CommunityDataInfo>();
			}
			return seqOf;
		}

		public int encode(OutputStream os) throws IOException {
			return encode(os, true);
		}

		public int encode(OutputStream os, boolean withTag) throws IOException {

			if (code != null) {
				for (int i = code.length - 1; i >= 0; i--) {
					os.write(code[i]);
				}
				if (withTag) {
					return tag.encode(os) + code.length;
				}
				return code.length;
			}

			int codeLength = 0;
			for (int i = (seqOf.size() - 1); i >= 0; i--) {
				codeLength += seqOf.get(i).encode(os, true);
			}

			codeLength += BerLength.encodeLength(os, codeLength);

			if (withTag) {
				codeLength += tag.encode(os);
			}

			return codeLength;
		}

		public int decode(InputStream is) throws IOException {
			return decode(is, true);
		}

		public int decode(InputStream is, boolean withTag) throws IOException {
			int codeLength = 0;
			int subCodeLength = 0;
			if (withTag) {
				codeLength += tag.decodeAndCheck(is);
			}

			BerLength length = new BerLength();
			codeLength += length.decode(is);
			int totalLength = length.val;

			while (subCodeLength < totalLength) {
				chargingcdr.CommunityDataInfo element = new chargingcdr.CommunityDataInfo();
				subCodeLength += element.decode(is, true);
				seqOf.add(element);
			}
			if (subCodeLength != totalLength) {
				throw new IOException("Decoded SequenceOf or SetOf has wrong length. Expected " + totalLength + " but has " + subCodeLength);

			}
			codeLength += subCodeLength;

			return codeLength;
		}

		public void encodeAndSave(int encodingSizeGuess) throws IOException {
			ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
			encode(os, false);
			code = os.getArray();
		}

		public String toString() {
			StringBuilder sb = new StringBuilder();
			appendAsString(sb, 0);
			return sb.toString();
		}

		public void appendAsString(StringBuilder sb, int indentLevel) {

			sb.append("{\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			if (seqOf == null) {
				sb.append("null");
			}
			else {
				Iterator<chargingcdr.CommunityDataInfo> it = seqOf.iterator();
				if (it.hasNext()) {
					it.next().appendAsString(sb, indentLevel + 1);
					while (it.hasNext()) {
						sb.append(",\n");
						for (int i = 0; i < indentLevel + 1; i++) {
							sb.append("\t");
						}
						it.next().appendAsString(sb, indentLevel + 1);
					}
				}
			}

			sb.append("\n");
			for (int i = 0; i < indentLevel; i++) {
				sb.append("\t");
			}
			sb.append("}");
		}

	}

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private IMSI servedIMSI = null;
	private AddressString servedMSISDN = null;
	private AddressString serviceCenter = null;
	private NodeID nodeID = null;
	private LocalSequenceNumber localSequenceNumber = null;
	private TrafficCase trafficCase = null;
	private ServiceClass serviceClass = null;
	private MoneyAmount accountValueBefore = null;
	private MoneyAmount accountValueAfter = null;
	private MoneyAmount finalCharge = null;
	private CdrReason cdrReason = null;
	private TeleServiceCode teleServiceCode = null;
	private TimeStamp startOfChargingOfEvent = null;
	private FamilyAndFriendsIndicator familyAndFriendsIndicator = null;
	private NumberOfSDPInterrogations numberOfSDPInterrogations = null;
	private CurrencyType currencyType = null;
	private AddressString originatingLocationInfo = null;
	private AddressString accountNumber = null;
	private AddressString destinationNumber = null;
	private AccumulatorValueInfo accumulatorValueInfo = null;
	private DedicatedAccountInfo dedicatedAccountInfo = null;
	private TimeStamp eventTimeStamp = null;
	private NetworkID networkID = null;
	private CallReferenceNumber smsReferenceNumber = null;
	private AddressString mscAddress = null;
	private AddressString sgsnNumber = null;
	private AccountGroupID accountGroupID = null;
	private ServiceOfferings serviceOfferings = null;
	private CommunityDataInfo communityDataInfo = null;
	private AddressString calledPartyNumber = null;
	private CellID cellID = null;
	private LocationAreaID locationAreaID = null;
	private CategorizationInformation categorizationInformation = null;
	private RatedDurations ratedDurations = null;
	private IndividualPriceFactorHistory individualPriceFactorHistory = null;
	private AddressString originalCalledPartyNumber = null;
	
	public SCFSMSMORecord() {
	}

	public SCFSMSMORecord(byte[] code) {
		this.code = code;
	}

	public void setServedIMSI(IMSI servedIMSI) {
		this.servedIMSI = servedIMSI;
	}

	public IMSI getServedIMSI() {
		return servedIMSI;
	}

	public void setServedMSISDN(AddressString servedMSISDN) {
		this.servedMSISDN = servedMSISDN;
	}

	public AddressString getServedMSISDN() {
		return servedMSISDN;
	}

	public void setServiceCenter(AddressString serviceCenter) {
		this.serviceCenter = serviceCenter;
	}

	public AddressString getServiceCenter() {
		return serviceCenter;
	}

	public void setNodeID(NodeID nodeID) {
		this.nodeID = nodeID;
	}

	public NodeID getNodeID() {
		return nodeID;
	}

	public void setLocalSequenceNumber(LocalSequenceNumber localSequenceNumber) {
		this.localSequenceNumber = localSequenceNumber;
	}

	public LocalSequenceNumber getLocalSequenceNumber() {
		return localSequenceNumber;
	}

	public void setTrafficCase(TrafficCase trafficCase) {
		this.trafficCase = trafficCase;
	}

	public TrafficCase getTrafficCase() {
		return trafficCase;
	}

	public void setServiceClass(ServiceClass serviceClass) {
		this.serviceClass = serviceClass;
	}

	public ServiceClass getServiceClass() {
		return serviceClass;
	}

	public void setAccountValueBefore(MoneyAmount accountValueBefore) {
		this.accountValueBefore = accountValueBefore;
	}

	public MoneyAmount getAccountValueBefore() {
		return accountValueBefore;
	}

	public void setAccountValueAfter(MoneyAmount accountValueAfter) {
		this.accountValueAfter = accountValueAfter;
	}

	public MoneyAmount getAccountValueAfter() {
		return accountValueAfter;
	}

	public void setFinalCharge(MoneyAmount finalCharge) {
		this.finalCharge = finalCharge;
	}

	public MoneyAmount getFinalCharge() {
		return finalCharge;
	}

	public void setCdrReason(CdrReason cdrReason) {
		this.cdrReason = cdrReason;
	}

	public CdrReason getCdrReason() {
		return cdrReason;
	}

	public void setTeleServiceCode(TeleServiceCode teleServiceCode) {
		this.teleServiceCode = teleServiceCode;
	}

	public TeleServiceCode getTeleServiceCode() {
		return teleServiceCode;
	}

	public void setStartOfChargingOfEvent(TimeStamp startOfChargingOfEvent) {
		this.startOfChargingOfEvent = startOfChargingOfEvent;
	}

	public TimeStamp getStartOfChargingOfEvent() {
		return startOfChargingOfEvent;
	}

	public void setFamilyAndFriendsIndicator(FamilyAndFriendsIndicator familyAndFriendsIndicator) {
		this.familyAndFriendsIndicator = familyAndFriendsIndicator;
	}

	public FamilyAndFriendsIndicator getFamilyAndFriendsIndicator() {
		return familyAndFriendsIndicator;
	}

	public void setNumberOfSDPInterrogations(NumberOfSDPInterrogations numberOfSDPInterrogations) {
		this.numberOfSDPInterrogations = numberOfSDPInterrogations;
	}

	public NumberOfSDPInterrogations getNumberOfSDPInterrogations() {
		return numberOfSDPInterrogations;
	}

	public void setCurrencyType(CurrencyType currencyType) {
		this.currencyType = currencyType;
	}

	public CurrencyType getCurrencyType() {
		return currencyType;
	}

	public void setOriginatingLocationInfo(AddressString originatingLocationInfo) {
		this.originatingLocationInfo = originatingLocationInfo;
	}

	public AddressString getOriginatingLocationInfo() {
		return originatingLocationInfo;
	}

	public void setAccountNumber(AddressString accountNumber) {
		this.accountNumber = accountNumber;
	}

	public AddressString getAccountNumber() {
		return accountNumber;
	}

	public void setDestinationNumber(AddressString destinationNumber) {
		this.destinationNumber = destinationNumber;
	}

	public AddressString getDestinationNumber() {
		return destinationNumber;
	}

	public void setAccumulatorValueInfo(AccumulatorValueInfo accumulatorValueInfo) {
		this.accumulatorValueInfo = accumulatorValueInfo;
	}

	public AccumulatorValueInfo getAccumulatorValueInfo() {
		return accumulatorValueInfo;
	}

	public void setDedicatedAccountInfo(DedicatedAccountInfo dedicatedAccountInfo) {
		this.dedicatedAccountInfo = dedicatedAccountInfo;
	}

	public DedicatedAccountInfo getDedicatedAccountInfo() {
		return dedicatedAccountInfo;
	}

	public void setEventTimeStamp(TimeStamp eventTimeStamp) {
		this.eventTimeStamp = eventTimeStamp;
	}

	public TimeStamp getEventTimeStamp() {
		return eventTimeStamp;
	}

	public void setNetworkID(NetworkID networkID) {
		this.networkID = networkID;
	}

	public NetworkID getNetworkID() {
		return networkID;
	}

	public void setSmsReferenceNumber(CallReferenceNumber smsReferenceNumber) {
		this.smsReferenceNumber = smsReferenceNumber;
	}

	public CallReferenceNumber getSmsReferenceNumber() {
		return smsReferenceNumber;
	}

	public void setMscAddress(AddressString mscAddress) {
		this.mscAddress = mscAddress;
	}

	public AddressString getMscAddress() {
		return mscAddress;
	}

	public void setSgsnNumber(AddressString sgsnNumber) {
		this.sgsnNumber = sgsnNumber;
	}

	public AddressString getSgsnNumber() {
		return sgsnNumber;
	}

	public void setAccountGroupID(AccountGroupID accountGroupID) {
		this.accountGroupID = accountGroupID;
	}

	public AccountGroupID getAccountGroupID() {
		return accountGroupID;
	}

	public void setServiceOfferings(ServiceOfferings serviceOfferings) {
		this.serviceOfferings = serviceOfferings;
	}

	public ServiceOfferings getServiceOfferings() {
		return serviceOfferings;
	}

	public void setCommunityDataInfo(CommunityDataInfo communityDataInfo) {
		this.communityDataInfo = communityDataInfo;
	}

	public CommunityDataInfo getCommunityDataInfo() {
		return communityDataInfo;
	}

	public void setCalledPartyNumber(AddressString calledPartyNumber) {
		this.calledPartyNumber = calledPartyNumber;
	}

	public AddressString getCalledPartyNumber() {
		return calledPartyNumber;
	}

	public void setCellID(CellID cellID) {
		this.cellID = cellID;
	}

	public CellID getCellID() {
		return cellID;
	}

	public void setLocationAreaID(LocationAreaID locationAreaID) {
		this.locationAreaID = locationAreaID;
	}

	public LocationAreaID getLocationAreaID() {
		return locationAreaID;
	}

	public void setCategorizationInformation(CategorizationInformation categorizationInformation) {
		this.categorizationInformation = categorizationInformation;
	}

	public CategorizationInformation getCategorizationInformation() {
		return categorizationInformation;
	}

	public void setRatedDurations(RatedDurations ratedDurations) {
		this.ratedDurations = ratedDurations;
	}

	public RatedDurations getRatedDurations() {
		return ratedDurations;
	}

	public void setIndividualPriceFactorHistory(IndividualPriceFactorHistory individualPriceFactorHistory) {
		this.individualPriceFactorHistory = individualPriceFactorHistory;
	}

	public IndividualPriceFactorHistory getIndividualPriceFactorHistory() {
		return individualPriceFactorHistory;
	}

	public void setOriginalCalledPartyNumber(AddressString originalCalledPartyNumber) {
		this.originalCalledPartyNumber = originalCalledPartyNumber;
	}

	public AddressString getOriginalCalledPartyNumber() {
		return originalCalledPartyNumber;
	}

	public int encode(OutputStream os) throws IOException {
		return encode(os, true);
	}

	public int encode(OutputStream os, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				os.write(code[i]);
			}
			if (withTag) {
				return tag.encode(os) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (originalCalledPartyNumber != null) {
			codeLength += originalCalledPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 35
			os.write(0x23);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (individualPriceFactorHistory != null) {
			codeLength += individualPriceFactorHistory.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 34
			os.write(0x22);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (ratedDurations != null) {
			codeLength += ratedDurations.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 33
			os.write(0x21);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (categorizationInformation != null) {
			codeLength += categorizationInformation.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 32
			os.write(0x20);
			os.write(0xBF);
			codeLength += 2;
		}
		
		if (locationAreaID != null) {
			codeLength += locationAreaID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 31
			os.write(0x1F);
			os.write(0x9F);
			codeLength += 2;
		}
		
		if (cellID != null) {
			codeLength += cellID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 30
			os.write(0x9E);
			codeLength += 1;
		}
		
		if (calledPartyNumber != null) {
			codeLength += calledPartyNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 29
			os.write(0x9D);
			codeLength += 1;
		}
		
		if (communityDataInfo != null) {
			codeLength += communityDataInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 28
			os.write(0xBC);
			codeLength += 1;
		}
		
		if (serviceOfferings != null) {
			codeLength += serviceOfferings.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 27
			os.write(0x9B);
			codeLength += 1;
		}
		
		if (accountGroupID != null) {
			codeLength += accountGroupID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 26
			os.write(0x9A);
			codeLength += 1;
		}
		
		if (sgsnNumber != null) {
			codeLength += sgsnNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 25
			os.write(0x99);
			codeLength += 1;
		}
		
		if (mscAddress != null) {
			codeLength += mscAddress.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 24
			os.write(0x98);
			codeLength += 1;
		}
		
		if (smsReferenceNumber != null) {
			codeLength += smsReferenceNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 23
			os.write(0x97);
			codeLength += 1;
		}
		
		if (networkID != null) {
			codeLength += networkID.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 22
			os.write(0x96);
			codeLength += 1;
		}
		
		codeLength += eventTimeStamp.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 21
		os.write(0x95);
		codeLength += 1;
		
		if (dedicatedAccountInfo != null) {
			codeLength += dedicatedAccountInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 20
			os.write(0xB4);
			codeLength += 1;
		}
		
		if (accumulatorValueInfo != null) {
			codeLength += accumulatorValueInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, CONSTRUCTED, 19
			os.write(0xB3);
			codeLength += 1;
		}
		
		codeLength += destinationNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 18
		os.write(0x92);
		codeLength += 1;
		
		if (accountNumber != null) {
			codeLength += accountNumber.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 17
			os.write(0x91);
			codeLength += 1;
		}
		
		if (originatingLocationInfo != null) {
			codeLength += originatingLocationInfo.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 16
			os.write(0x90);
			codeLength += 1;
		}
		
		if (currencyType != null) {
			codeLength += currencyType.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 15
			os.write(0x8F);
			codeLength += 1;
		}
		
		codeLength += numberOfSDPInterrogations.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 14
		os.write(0x8E);
		codeLength += 1;
		
		if (familyAndFriendsIndicator != null) {
			codeLength += familyAndFriendsIndicator.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 13
			os.write(0x8D);
			codeLength += 1;
		}
		
		if (startOfChargingOfEvent != null) {
			codeLength += startOfChargingOfEvent.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 12
			os.write(0x8C);
			codeLength += 1;
		}
		
		if (teleServiceCode != null) {
			codeLength += teleServiceCode.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 11
			os.write(0x8B);
			codeLength += 1;
		}
		
		codeLength += cdrReason.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 10
		os.write(0x8A);
		codeLength += 1;
		
		if (finalCharge != null) {
			codeLength += finalCharge.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 9
			os.write(0x89);
			codeLength += 1;
		}
		
		if (accountValueAfter != null) {
			codeLength += accountValueAfter.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 8
			os.write(0x88);
			codeLength += 1;
		}
		
		if (accountValueBefore != null) {
			codeLength += accountValueBefore.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 7
			os.write(0x87);
			codeLength += 1;
		}
		
		if (serviceClass != null) {
			codeLength += serviceClass.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 6
			os.write(0x86);
			codeLength += 1;
		}
		
		if (trafficCase != null) {
			codeLength += trafficCase.encode(os, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 5
			os.write(0x85);
			codeLength += 1;
		}
		
		codeLength += localSequenceNumber.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 4
		os.write(0x84);
		codeLength += 1;
		
		codeLength += nodeID.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 3
		os.write(0x83);
		codeLength += 1;
		
		codeLength += serviceCenter.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		os.write(0x82);
		codeLength += 1;
		
		codeLength += servedMSISDN.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		os.write(0x81);
		codeLength += 1;
		
		codeLength += servedIMSI.encode(os, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		os.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(os, codeLength);

		if (withTag) {
			codeLength += tag.encode(os);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			servedIMSI = new IMSI();
			subCodeLength += servedIMSI.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			servedMSISDN = new AddressString();
			subCodeLength += servedMSISDN.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			serviceCenter = new AddressString();
			subCodeLength += serviceCenter.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			nodeID = new NodeID();
			subCodeLength += nodeID.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			localSequenceNumber = new LocalSequenceNumber();
			subCodeLength += localSequenceNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			trafficCase = new TrafficCase();
			subCodeLength += trafficCase.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 6)) {
			serviceClass = new ServiceClass();
			subCodeLength += serviceClass.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 7)) {
			accountValueBefore = new MoneyAmount();
			subCodeLength += accountValueBefore.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 8)) {
			accountValueAfter = new MoneyAmount();
			subCodeLength += accountValueAfter.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 9)) {
			finalCharge = new MoneyAmount();
			subCodeLength += finalCharge.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 10)) {
			cdrReason = new CdrReason();
			subCodeLength += cdrReason.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 11)) {
			teleServiceCode = new TeleServiceCode();
			subCodeLength += teleServiceCode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 12)) {
			startOfChargingOfEvent = new TimeStamp();
			subCodeLength += startOfChargingOfEvent.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 13)) {
			familyAndFriendsIndicator = new FamilyAndFriendsIndicator();
			subCodeLength += familyAndFriendsIndicator.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 14)) {
			numberOfSDPInterrogations = new NumberOfSDPInterrogations();
			subCodeLength += numberOfSDPInterrogations.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 15)) {
			currencyType = new CurrencyType();
			subCodeLength += currencyType.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 16)) {
			originatingLocationInfo = new AddressString();
			subCodeLength += originatingLocationInfo.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 17)) {
			accountNumber = new AddressString();
			subCodeLength += accountNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 18)) {
			destinationNumber = new AddressString();
			subCodeLength += destinationNumber.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 19)) {
			accumulatorValueInfo = new AccumulatorValueInfo();
			subCodeLength += accumulatorValueInfo.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 20)) {
			dedicatedAccountInfo = new DedicatedAccountInfo();
			subCodeLength += dedicatedAccountInfo.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 21)) {
			eventTimeStamp = new TimeStamp();
			subCodeLength += eventTimeStamp.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 22)) {
			networkID = new NetworkID();
			subCodeLength += networkID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 23)) {
			smsReferenceNumber = new CallReferenceNumber();
			subCodeLength += smsReferenceNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 24)) {
			mscAddress = new AddressString();
			subCodeLength += mscAddress.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 25)) {
			sgsnNumber = new AddressString();
			subCodeLength += sgsnNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 26)) {
			accountGroupID = new AccountGroupID();
			subCodeLength += accountGroupID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 27)) {
			serviceOfferings = new ServiceOfferings();
			subCodeLength += serviceOfferings.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 28)) {
			communityDataInfo = new CommunityDataInfo();
			subCodeLength += communityDataInfo.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 29)) {
			calledPartyNumber = new AddressString();
			subCodeLength += calledPartyNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 30)) {
			cellID = new CellID();
			subCodeLength += cellID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 31)) {
			locationAreaID = new LocationAreaID();
			subCodeLength += locationAreaID.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 32)) {
			categorizationInformation = new CategorizationInformation();
			subCodeLength += categorizationInformation.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 33)) {
			ratedDurations = new RatedDurations();
			subCodeLength += ratedDurations.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 34)) {
			individualPriceFactorHistory = new IndividualPriceFactorHistory();
			subCodeLength += individualPriceFactorHistory.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 35)) {
			originalCalledPartyNumber = new AddressString();
			subCodeLength += originalCalledPartyNumber.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream os = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(os, false);
		code = os.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (servedIMSI != null) {
			sb.append("servedIMSI: ").append(servedIMSI);
		}
		else {
			sb.append("servedIMSI: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (servedMSISDN != null) {
			sb.append("servedMSISDN: ").append(servedMSISDN);
		}
		else {
			sb.append("servedMSISDN: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (serviceCenter != null) {
			sb.append("serviceCenter: ").append(serviceCenter);
		}
		else {
			sb.append("serviceCenter: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (nodeID != null) {
			sb.append("nodeID: ").append(nodeID);
		}
		else {
			sb.append("nodeID: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (localSequenceNumber != null) {
			sb.append("localSequenceNumber: ").append(localSequenceNumber);
		}
		else {
			sb.append("localSequenceNumber: <empty-required-field>");
		}
		
		if (trafficCase != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("trafficCase: ").append(trafficCase);
		}
		
		if (serviceClass != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceClass: ").append(serviceClass);
		}
		
		if (accountValueBefore != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueBefore: ").append(accountValueBefore);
		}
		
		if (accountValueAfter != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountValueAfter: ").append(accountValueAfter);
		}
		
		if (finalCharge != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("finalCharge: ").append(finalCharge);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (cdrReason != null) {
			sb.append("cdrReason: ").append(cdrReason);
		}
		else {
			sb.append("cdrReason: <empty-required-field>");
		}
		
		if (teleServiceCode != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("teleServiceCode: ").append(teleServiceCode);
		}
		
		if (startOfChargingOfEvent != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("startOfChargingOfEvent: ").append(startOfChargingOfEvent);
		}
		
		if (familyAndFriendsIndicator != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("familyAndFriendsIndicator: ").append(familyAndFriendsIndicator);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (numberOfSDPInterrogations != null) {
			sb.append("numberOfSDPInterrogations: ").append(numberOfSDPInterrogations);
		}
		else {
			sb.append("numberOfSDPInterrogations: <empty-required-field>");
		}
		
		if (currencyType != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("currencyType: ").append(currencyType);
		}
		
		if (originatingLocationInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originatingLocationInfo: ").append(originatingLocationInfo);
		}
		
		if (accountNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountNumber: ").append(accountNumber);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (destinationNumber != null) {
			sb.append("destinationNumber: ").append(destinationNumber);
		}
		else {
			sb.append("destinationNumber: <empty-required-field>");
		}
		
		if (accumulatorValueInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accumulatorValueInfo: ");
			accumulatorValueInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (dedicatedAccountInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("dedicatedAccountInfo: ");
			dedicatedAccountInfo.appendAsString(sb, indentLevel + 1);
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (eventTimeStamp != null) {
			sb.append("eventTimeStamp: ").append(eventTimeStamp);
		}
		else {
			sb.append("eventTimeStamp: <empty-required-field>");
		}
		
		if (networkID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("networkID: ").append(networkID);
		}
		
		if (smsReferenceNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("smsReferenceNumber: ").append(smsReferenceNumber);
		}
		
		if (mscAddress != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("mscAddress: ").append(mscAddress);
		}
		
		if (sgsnNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("sgsnNumber: ").append(sgsnNumber);
		}
		
		if (accountGroupID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("accountGroupID: ").append(accountGroupID);
		}
		
		if (serviceOfferings != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("serviceOfferings: ").append(serviceOfferings);
		}
		
		if (communityDataInfo != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("communityDataInfo: ");
			communityDataInfo.appendAsString(sb, indentLevel + 1);
		}
		
		if (calledPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("calledPartyNumber: ").append(calledPartyNumber);
		}
		
		if (cellID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("cellID: ").append(cellID);
		}
		
		if (locationAreaID != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("locationAreaID: ").append(locationAreaID);
		}
		
		if (categorizationInformation != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("categorizationInformation: ");
			categorizationInformation.appendAsString(sb, indentLevel + 1);
		}
		
		if (ratedDurations != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ratedDurations: ");
			ratedDurations.appendAsString(sb, indentLevel + 1);
		}
		
		if (individualPriceFactorHistory != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("individualPriceFactorHistory: ");
			individualPriceFactorHistory.appendAsString(sb, indentLevel + 1);
		}
		
		if (originalCalledPartyNumber != null) {
			sb.append(",\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("originalCalledPartyNumber: ").append(originalCalledPartyNumber);
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

